id = "sonderr"
name = "Sonderr"
description = "The open source coding agent."
version = "7.5.6"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/Sonderr-Org/sonderr"

[agent_servers.sonderr]
name = "Sonderr"
icon = "./icons/sonderr.svg"

[agent_servers.sonderr.targets.darwin-aarch64]
archive = "https://github.com/Sonderr-Org/sonderr/releases/download/v7.5.6/sonderr-darwin-arm64.zip"
cmd = "./sonderr"
args = ["acp"]

[agent_servers.sonderr.targets.darwin-x86_64]
archive = "https://github.com/Sonderr-Org/sonderr/releases/download/v7.5.6/sonderr-darwin-x64.zip"
cmd = "./sonderr"
args = ["acp"]

[agent_servers.sonderr.targets.linux-aarch64]
archive = "https://github.com/Sonderr-Org/sonderr/releases/download/v7.5.6/sonderr-linux-arm64.tar.gz"
cmd = "./sonderr"
args = ["acp"]

[agent_servers.sonderr.targets.linux-x86_64]
archive = "https://github.com/Sonderr-Org/sonderr/releases/download/v7.5.6/sonderr-linux-x64.tar.gz"
cmd = "./sonderr"
args = ["acp"]

[agent_servers.sonderr.targets.windows-x86_64]
archive = "https://github.com/Sonderr-Org/sonderr/releases/download/v7.5.6/sonderr-windows-x64.zip"
cmd = "./sonderr.exe"
args = ["acp"]
